### ISSUE TITLE
Use Report instead of Action to trigger MBOM Export

### ISSUE THREAD

**Issue by AngelaIp** [ArasLabs/mbom-export#6]
The current version uses an additional Action to trigger the MBOM Export. 
But users are used to creating reports via the report menu. The action menu is inteded for other things.

Solution:
Use an additional report item to start the method to improve user experience:
![image](https://user-images.githubusercontent.com/32091085/53556542-5ddb9f80-3b44-11e9-84c1-7fa4ed6003a1.png)

**Comment by EliJDonahue** [comment]
I actually bounced back and forth between using an Action and a Report when developing this project. I couldn't decide whether the use case should be treated as an action (export this data) or a report (show me a snapshot of this data). Ultimately I suppose it boils down to what the users want to see. 

It would be easy enough to include the dummy report in the project as an option for those whose users want to use the report option. I actually already have this report in my dev environment. I'll add it to the package and update the install instructions to include steps for activating the optional report.

**Comment by EliJDonahue** [comment]
Fixed in PR #10. Included in release [v1.1.0](https://github.com/ArasLabs/mbom-export/releases/tag/v1.1.0).

**Comment by AngelaIp** [comment]
Uh wait! You´re right! An Action fits well...but a Report also. During my tests I instinctively looked in the Report menu first, because I compared this project to the OOTB XSLT reports used in Parts.

It´s really not an easy question, espcially when we take a look at other Aras applications that can publish something.
MPP -> Result is published according to dialog settings -> CUI button in Process Plan
TechDoc -> Result is published according to dialog settings -> Action
PE ->  Result is published directly -> Report
Publish a Graph -> Action
...

Finding the right answer for this one is probably a challanging task for UX designers. I think your CUI buttion idea is the best approach, as users don´t need to look into any menu at all.
